Banking_Model:
  outputs:
    dev:
      account: xm93452.central-india
      database: BANK_MODEL
      password: *********
      role: ACCOUNTADMIN
      schema: staging
      threads: 1
      type: snowflake
      user: ********
      warehouse: COMPUTE_WH
  target: dev
